import type { ImageUrlOptions } from "@imgwire/js";
import { describe, expect, it } from "vitest";
import {
  omitImageTransformProps,
  pickImageUrlOptions,
} from "../src/utils/image-transforms.ts";

const transformProps = {
  preset: "thumbnail",
  adjust: "1:1:1",
  a: { brightness: 1, saturation: 1, color: 1 },
  background: "#ffffff",
  bg: "#000000",
  background_alpha: 0.5,
  bga: "0.5",
  blur: true,
  bl: 2,
  brightness: 1,
  br: "1",
  color_profile: "srgb",
  cp: "srgb",
  icc: "keep",
  colorize: "#ffffff",
  col: "#000000",
  contrast: 1,
  co: { multiplier: 1, pivot: 0.5 },
  crop: "100:100",
  c: { width: 100, height: 100 },
  dpi: 72,
  dpr: 2,
  duotone: "#000000:#ffffff",
  dt: { shadowColor: "#000000", highlightColor: "#ffffff" },
  enlarge: true,
  el: "true",
  extend: "1",
  ex: { top: 1 },
  extend_aspect_ratio: "16:9",
  extend_ar: 1.777,
  exar: { width: 16, height: 9 },
  flip: "horizontal",
  fl: "true:false",
  format: "webp",
  f: "jpg",
  extension: "png",
  ext: "avif",
  gradient: "#000000,#ffffff",
  gr: { colors: ["#000000", "#ffffff"], angle: 90 },
  gravity: "center",
  g: "noea",
  height: 400,
  h: "400",
  hue: 90,
  hu: "90",
  keep_copyright: true,
  kcr: "true",
  lightness: 1,
  l: "1",
  "min-height": 200,
  min_height: "200",
  mh: 200,
  "min-width": 300,
  min_width: "300",
  mw: 300,
  monochrome: true,
  mc: "#ffffff",
  negate: true,
  neg: { alpha: true },
  normalize: true,
  normalise: "1:99",
  norm: { lower: 1, upper: 99 },
  padding: 10,
  pd: "1:2:3:4",
  pixelate: 8,
  pix: "8",
  quality: 80,
  q: "80",
  resizing_algorithm: "lanczos3",
  ra: "nearest",
  resizing_type: "cover",
  rotate: 90,
  rot: { angle: 90 },
  saturation: 1,
  sa: "1",
  sharpen: true,
  sh: { sigma: 1 },
  strip_color_profile: true,
  scp: "true",
  strip_metadata: true,
  sm: "true",
  watermark: "logo",
  wm: { image_id: "logo" },
  watermark_position: "se:-1:-1:0.5",
  watermark_offset: { gravity: "se" },
  wmp: { gravity: "se", x: -1, y: -1 },
  watermark_rotate: 90,
  wm_rot: { angle: 90 },
  wmr: "90",
  watermark_shadow: true,
  wmsh: "#000000:2:1:1",
  watermark_size: "100:100",
  wms: { width: 100 },
  watermark_text: "hello",
  wmt: { text: "hello" },
  watermark_url: "https://example.com/logo.png",
  wmu: "aHR0cHM6Ly9leGFtcGxlLmNvbS9sb2dvLnBuZw==",
  width: 800,
  w: "800",
  zoom: 2,
  z: { factor: 2 },
} satisfies Record<keyof ImageUrlOptions, unknown>;

describe("image transform utilities", () => {
  it("picks every @imgwire/js 0.3.0 image URL transform prop", () => {
    expect(
      pickImageUrlOptions({
        ...transformProps,
        resizeMode: "cover",
      }),
    ).toEqual(transformProps);
  });

  it("omits every transform prop from React Native image props", () => {
    expect(
      omitImageTransformProps({
        id: "img_123",
        url: "cdn.imgwire.dev/example",
        ...transformProps,
        resizeMode: "cover",
      }),
    ).toEqual({ resizeMode: "cover" });
  });
});
