import type {
  AdjustValue,
  ImageSchema,
  ImagesCreateOptions,
  ImageUrlOptions,
  ImageUrlPreset,
  ImgwireClient,
  ImgwireClientOptions,
  ImgwireImage,
  ImagesUploadOptions,
  BooleanLike,
  ChromaSubsamplingValue,
  ColorValue,
  ContrastValue,
  CropValue,
  DuotoneValue,
  ExtendAspectRatioValue,
  ExtendValue,
  FlipValue,
  GradientValue,
  GravityValue,
  JsonValue,
  NegateValue,
  NormalizeValue,
  OutputFormat,
  PaddingValue,
  ProgressiveValue,
  QualityValue,
  ResizingAlgorithm,
  ResizingType,
  RotateAngle,
  RotateValue,
  SharpenValue,
  WatermarkPositionValue,
  WatermarkShadowValue,
  WatermarkSizeValue,
  WatermarkTextValue,
  WatermarkValue,
  ZoomValue,
} from "@imgwire/js";
import type { UploadableFile, UploadProgress } from "./hooks/useUpload.ts";

export type ClientOptions = ImgwireClientOptions;
export type ImgwireImageData = ImgwireImage;
export type ImageMetadata = ImageSchema;
export type ImageTransforms = ImageUrlOptions;
export type CreateImageOptions = ImagesCreateOptions;
export type UploadOptions = ImagesUploadOptions;
export type ImgwireReactNativeClient = ImgwireClient;
export type { UploadableFile, UploadProgress };
export type {
  AdjustValue,
  BooleanLike,
  ChromaSubsamplingValue,
  ColorValue,
  ContrastValue,
  CropValue,
  DuotoneValue,
  ExtendAspectRatioValue,
  ExtendValue,
  FlipValue,
  GradientValue,
  GravityValue,
  ImageUrlPreset,
  JsonValue,
  NegateValue,
  NormalizeValue,
  OutputFormat,
  PaddingValue,
  ProgressiveValue,
  QualityValue,
  ResizingAlgorithm,
  ResizingType,
  RotateAngle,
  RotateValue,
  SharpenValue,
  WatermarkPositionValue,
  WatermarkShadowValue,
  WatermarkSizeValue,
  WatermarkTextValue,
  WatermarkValue,
  ZoomValue,
};
